@isbn=9782200611583
@user=John Doe

# P1

### Get all books
GET {{baseUrl}}/v1/books
Ocp-Apim-Subscription-Key: {{apimKey}}

### Search for a book globally by ISBN
GET {{baseUrl}}/v1/books/{{isbn}}
Ocp-Apim-Subscription-Key: {{apimKey}}

### Add a book to the collection
POST {{baseUrl}}/v1/books
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{apimKey}}

{
  "isbn": "9782200611583",
  "author": "Christophe",
  "title": "L'album Christophe"
}

### Lend a book to a user
PUT {{baseUrl}}/v1/books/{{isbn}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{apimKey}}

{
  "lentTo": "{{user}}"
}

### List the users
GET {{baseUrl}}/v1/users

### Register a book back
PUT {{baseUrl}}/v1/books/{{isbn}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{apimKey}}

{
  "lentTo": null
}

# P2

### List the books of a user
GET {{baseUrl}}/v1/books?user={{user}}

### Search for a user

# P3

### Add a user

### List the books lent to a user